//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp
    {
        public string eid { get; set; }
        public string ename { get; set; }
        public Nullable<int> age { get; set; }
        public string city { get; set; }
    }
}
